project3 Berezin
TheMLord/java-backend-course-2023-tinkoff pull request #9
Opened 2023-11-19 20:41 UTC by TheMLord

2023-11-19 21:39 UTC, TheMLord commented
не проходили тесты из за выводимого пути до файла в статистике, у меня относительно рабочей директории выводилось, пофиксил эту проблему. Надеюсь это не страшно, что эту проблему решил после 2:00

2023-11-19 22:31 UTC, TheMLord commented
Добавил readme к проекту и комментарии к коду

2023-11-19 22:35 UTC, TheMLord commented
Все таки тесты на гитхабе не проходят. Локально проходит. Я проверил, привязки никакой к путям на локальной машине нет, в статистике тоже пути пишутся правильно. 1 раз смог выполнить тест успешно, но когда я добавил редми и комменты к коду перестал проходить. Скорее всего не может найти файлы, хотя пути валидные. Не знаю даже как пофиксить

2023-11-19 22:43 UTC, TheMLord commented
Я понял в чем у тестов проблема. Некоторую статистику я храню промежуточно в Map. Видимо стримы недетерминированно добавляют туда элементы

2023-11-19 22:59 UTC, TheMLord commented
Пофиксил. Теперь мапки детерменированно парсяться. Вместо HashMap использую TreeMap

2023-11-26 17:34 UTC, kkkoltunov requested changes
программа функционируют корректно, за ридми респект, за комменты лайк, за то что сделал абстрактный `MarkupsLanguage` и от него унаследовал остальное, вообще красавчик

старайся делать методы по 10-15 строк максимум, не бойся дробить их, так код намного легче читать

однако, тестов хотелось бы больше и чтобы они были разбиты по какой-то логике отдельной, потому что сейчас они очень емкие, учти это в следующий раз

поставил оценку пока на платформе, но когда поправишь напиши мне в тг @kkkoltunov, я подниму

2023-11-26 17:34 UTC, kkkoltunov commented on src/test/java/edu/project3/TestProject3.java
> +    @Order(1)
за такое бан сразу, порядок надо убирать, тесты должны быть независимы друг от друга и от порядка исполнения)

2023-11-26 17:34 UTC, kkkoltunov commented on src/test/java/edu/project3/TestProject3.java
> +        var logFilePath = Path.of(TestProject3.class.getResource("/goldenMdResult.md").getPath());
давай писать где это возможно тесты по концепеции given-when-then, так выглядит понятнее и читабельнее https://habr.com/ru/articles/344588/

2023-12-10 21:04 UTC, merged